config/routes.rb
Babies::Application.routes.draw do
  root 'babies#index'
  resources :babies

end

app/models/baby.rb
class Baby < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  def self.get_new_snaps
    # Initialize a client and login
    snapcat = Snapcat::Client.new('facemerge')
    snapcat.login('catsdogs')
    user = snapcat.user

    snaps = user.snaps_received
    if snaps
      snaps.each do |s|
        media_response = snapcat.media_for(s.id)
        media = media_response.data[:media]
        if media
          if media.image?
            f = File.open("app/assets/images/#{Time.now.strftime("%Y-%d-%m")}-#{s.id}.#{media.file_extension}", 'w:ASCII-8BIT')
            f.write(media)
            f.close
            filename = File.basename(f)
            filename = "app/assets/images/" + filename
            parent = s.sender
            # other_parent = "aneeshusa"
          end
        end

        # Check if this parent1 exists
        # matches = Baby.find(:all, :conditions => { :parent1 => parent, :parent2 => other_parent})
        matches = Baby.all
        if matches.empty?
          # This initiator is not in the table yet, add the first parent
          # b = Baby.new(:parent1 => parent, :parent2 => other_parent, :img1 => filename )
          b = Baby.new({ :parent1 => parent, :img1 => filename })
          b.save
          # puts parent

          # # Send a snap to the second person to tell them what to do
          # provoke = File.open("app/assets/images/BabyBlendr.jpg", "rb").read
          # snapcat.send_media(provoke, other_parent, view_duration: 10)
        else
          b = matches[0]
          b.parent2 = parent
          b.img2 = filename
          b.save

          # Create baby and send it out to both parents
          created_baby = BabiesController.make_baby(b)

          final = File.open("app/assets/images/" + b.id.to_s + ".jpg", "rb").read #is this 8 bit color?
          snapcat.send_media(final, b.parent1, view_duration: 10)
          snapcat.send_media(final, b.parent2, view_duration: 10)
          b.destroy
        end
      end
    end
    snapcat.clear_feed
  end

  def self.make_baby(baby)
    link = "http://www.photofunia.com/lab/face_swap"
    img1 = File.open(baby.img1)
    img2 = File.open(baby.img2)

    agent = Mechanize.new
    page = agent.get(link)

    page1 = page.form_with(:method => 'POST') do |upload_form|
      upload_form.file_uploads[0].file_name = baby.img1
      upload_form.file_uploads[1].file_name = baby.img2
    end.submit

    img = "http://www.photofunia.com" + page1.link_with(:href => /^\/save\/.\/default\//).href

    page2 = agent.get(img)
    
    page2.save "app/assets/images/" + baby.id.to_s + '.jpg'
  end

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render action: 'show', status: :created, location: @baby }
      else
        format.html { render action: 'new' }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_params
      params.require(:baby).permit(:parent1, :parent2, :img1, :img2, :final)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_form.html.erb
<%= form_for(@baby) do |f| %>
  <% if @baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% @baby.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent1 %><br>
    <%= f.text_field :parent1 %>
  </div>
  <div class="field">
    <%= f.label :parent2 %><br>
    <%= f.text_field :parent2 %>
  </div>
  <div class="field">
    <%= f.label :img1 %><br>
    <%= f.text_field :img1 %>
  </div>
  <div class="field">
    <%= f.label :img2 %><br>
    <%= f.text_field :img2 %>
  </div>
  <div class="field">
    <%= f.label :final %><br>
    <%= f.text_field :final %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing baby</h1>

<%= render 'form' %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<h1>Listing babies</h1>

<table>
  <thead>
    <tr>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Img1</th>
      <th>Img2</th>
      <th>Final</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.parent1 %></td>
        <td><%= baby.parent2 %></td>
        <td><%= baby.img1 %></td>
        <td><%= baby.img2 %></td>
        <td><%= baby.final %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path %>

app/views/babies/new.html.erb
<h1>New baby</h1>

<%= render 'form' %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent1:</strong>
  <%= @baby.parent1 %>
</p>

<p>
  <strong>Parent2:</strong>
  <%= @baby.parent2 %>
</p>

<p>
  <strong>Img1:</strong>
  <%= @baby.img1 %>
</p>

<p>
  <strong>Img2:</strong>
  <%= @baby.img2 %>
</p>

<p>
  <strong>Final:</strong>
  <%= @baby.final %>
</p>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>